# Generated by Django 4.2.11 on 2024-04-01 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="receiver",
            new_name="recipient",
        ),
    ]
