# Generated by Django 4.2.11 on 2024-04-01 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0002_rename_receiver_transaction_recipient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentrequest",
            old_name="receiver",
            new_name="recipient",
        ),
    ]
