# Generated by Django 4.2.11 on 2024-04-02 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0004_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
