# Generated by Django 4.2.11 on 2024-04-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "register",
            "0002_alter_userprofile_balance_alter_userprofile_currency_and_more",
        ),
        ("payapp", "0005_delete_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_request",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to="register.userprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transactions",
                        to="register.userprofile",
                    ),
                ),
            ],
        ),
    ]
