# Generated by Django 4.2.11 on 2024-04-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0007_remove_paymentrequest_is_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="is_accepted",
            field=models.BooleanField(),
        ),
    ]
