# Generated by Django 4.2.11 on 2024-04-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0008_alter_paymentrequest_is_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="is_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
